apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-react-app

spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-react-app
  template:
    metadata:
      labels:
        app: my-react-app
    spec:
      containers:
        - name: my-react-app-container
          image: deepikkaa20/my-react-app:latest
          ports:
            - containerPort: 80
